[metadata]
creation_date = "2026/09/05"
integration = []
maturity = "development"
updated_date = "2026/09/05"

[rule]
actions = []
author = ["40064842"]
description = "Detects chmod permissions with process args 777"
enabled = false
exceptions_list = []
false_positives = []
filters = []
from = "now-6m"
index = [
    "apm-*-transaction*",
    "auditbeat-*",
    "endgame-*",
    "filebeat-*",
    "logs-*",
    "packetbeat-*",
    "traces-apm*",
    "winlogbeat-*",
    "-*elastic-cloud-logs-*",
]
interval = "5m"
language = "kuery"
license = ""
max_signals = 100
name = "Suspicious chmod 777"
references = []
related_integrations = []
required_fields = []
revision = 1
risk_score = 21
risk_score_mapping = []
rule_id = "37f902d4-8795-4bfc-817a-ad7066ce92b6"
setup = ""
severity = "low"
severity_mapping = []
tags = []
to = "now"
type = "query"
version = 1

query = '''
process.name: "chmod" and process.args : "777"
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1222"
name = "File and Directory Permissions Modification"
reference = "https://attack.mitre.org/techniques/T1222/"
subtechnique = []


[rule.threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
subtechnique = []


[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

[rule.meta]
kibana_siem_app_url = "https://splunk-query-ed242f.kb.us-west2.gcp.elastic-cloud.com/app/security"

